version: '1.0.0'
name: 'MindScapeAIO'
services:
  psql:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./psql-data:/var/lib/postgresql/data
      - ./psql/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  mindscape-backend:
    restart: always
    build: 
      context: ./CMU-IS432_BlogMindScapeBackend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - psql
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - SALT_ROUND=${SALT_ROUND}
      - DB_HOST=${DB_HOST}
  mindscape-frontend:
    build: 
      context: ./CMU-IS432_BlogMindScapeFrontend
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    expose:
      - 3005
    depends_on:
      - psql
      - mindscape-backend
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 17032:80
    expose:
      - 17032
    environment:
      - PGADMIN_DEFAULT_EMAIL=nbk2124.z@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ektjPdjzs8fSwA
    